# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 72f13a19e26006b75b1ad6cecfcdc04794084758e5b65d6277394544bde1d27f3431060043b02bd5052f26c1cd8f2dd52d9ec4b2471e22da90bd6652badaf91f

test:
  secret_key_base: 1cd1c45348a650546dd1d7c91ad92216401333d4c95da177bfb9ad45d7f8800171add0655e9f7ea8d19cf3b52f77ed3fe0d5151c46392f12f6114269ff2522e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 1cd1c45348a650546dd1d7c91ad92216401333d4c95da177bfb9ad45d7f8800171add0655e9f7ea8d19cf3b52f77ed3fe0d5151c46392f12f6114269ff2522e2
